# yaml-language-server: $schema=./linter-service.schema.json
global:
  exclude_paths:
    - "**/tests/*/target/**"
    - "**/tests/*/sarif.json"
linters:
  lizard:
    disabled: false
    languages:
      - javascript
      - typescript
  textlint:
    disabled: false
    preset_packages:
      - "textlint-rule-preset-ja-technical-writing@12.0.2"
      - "@textlint-ja/textlint-rule-preset-ai-writing@1.6.3"
