name: Taplo

on:
  workflow_call:
    outputs:
      comment_body_base64:
        description: Base64-encoded markdown section for taplo
        value: ${{ jobs.taplo.outputs.comment_body_base64 }}
      conclusion:
        description: success or failure
        value: ${{ jobs.taplo.outputs.conclusion }}
    secrets:
      CHECKER_APP_ID:
        required: true
      CHECKER_PRIVATE_KEY:
        required: true

permissions: {}

jobs:
  taplo:
    uses: ./.github/workflows/lint-common.yml
    secrets:
      CHECKER_APP_ID: ${{ secrets.CHECKER_APP_ID }}
      CHECKER_PRIVATE_KEY: ${{ secrets.CHECKER_PRIVATE_KEY }}
    with:
      linter-name: taplo
