name: Actionlint

on:
  workflow_call:
    inputs:
      changed-files-json:
        required: true
        type: string
      source-head-sha:
        required: true
        type: string
      source-owner:
        required: true
        type: string
      source-repo:
        required: true
        type: string
    outputs:
      comment_body_base64:
        description: Base64-encoded markdown section for actionlint
        value: ${{ jobs.actionlint.outputs.comment_body_base64 }}
      conclusion:
        description: success or failure
        value: ${{ jobs.actionlint.outputs.conclusion }}
    secrets:
      CHECKER_APP_ID:
        required: true
      CHECKER_PRIVATE_KEY:
        required: true

permissions: {}

jobs:
  actionlint:
    uses: ./.github/workflows/lint-common.yml
    secrets: inherit
    with:
      changed-files-json: ${{ inputs.changed-files-json }}
      linter-name: actionlint
      source-head-sha: ${{ inputs.source-head-sha }}
      source-owner: ${{ inputs.source-owner }}
      source-repo: ${{ inputs.source-repo }}
