name: Actionlint

on:
  workflow_call:
    inputs:
      changed-files-json:
        required: true
        type: string
      check-run-external-id:
        required: true
        type: string
      check-run-name:
        required: true
        type: string
      pr-owner:
        required: true
        type: string
      pr-repo:
        required: true
        type: string
      pull-request-number:
        required: true
        type: string
      source-head-sha:
        required: true
        type: string
      source-owner:
        required: true
        type: string
      source-repo:
        required: true
        type: string
    secrets:
      CHECKER_APP_ID:
        required: true
      CHECKER_PRIVATE_KEY:
        required: true

permissions: {}

jobs:
  actionlint:
    uses: ./.github/workflows/lint-common.yml
    secrets: inherit
    with:
      changed-files-json: ${{ inputs.changed-files-json }}
      check-run-external-id: ${{ inputs.check-run-external-id }}
      check-run-name: ${{ inputs.check-run-name }}
      linter-name: actionlint
      pr-owner: ${{ inputs.pr-owner }}
      pr-repo: ${{ inputs.pr-repo }}
      pull-request-number: ${{ inputs.pull-request-number }}
      source-head-sha: ${{ inputs.source-head-sha }}
      source-owner: ${{ inputs.source-owner }}
      source-repo: ${{ inputs.source-repo }}
